max_tokens_num: 100
min_number_of_patterns: 1
max_number_of_patterns: 1
min_number_of_actions: 1
max_number_of_actions: 1000
min_number_of_changed_classes: 1
max_number_of_changed_classes: 1
min_number_of_changed_methods: 1
max_number_of_changed_methods: 1
min_number_of_changed_files: 1
max_number_of_changed_files: 1